Repository sparkpointio/sparkagent-launchpad, pull requests merged in 2025-03, with the labels that each got.

#115 Disable crypto conversion for the meantime
  app/lib/utils/utils.ts
Labels: !!!

#117 Re-enable Crypto Conversion Fetching and Improvements
  app/components/AgentCard.tsx
  app/components/AgentStats.tsx
  app/lib/utils/utils.ts
Labels: !!!, mainnet

#118 Update Forum API URLs
  app/api/forums/fetch-forum-messages-count/route.tsx
  app/api/forums/fetch-forum-messages-via-starting-index-number-of-messages-and-direction/route.tsx
Labels: bug fix, mainnet

#120 Fix hardcoded Arbiscan link
  app/components/AgentCard.tsx
  app/components/AgentStats.tsx
Labels: !!!, mainnet

#121 Add updating of theme color of ThirdWeb UI
  app/components/Header.tsx
Labels: !!!, mainnet

#124 Further app optimizations
  app/components/AgentCard.tsx
  app/components/AgentStats.tsx
  app/components/ForumEntry.tsx
  app/components/Hero.tsx
  app/layout.tsx
Labels: !!, mainnet

#125 Implement dynamic configuration of mainnet and testnet via environment variables
  .env.example
  app/agent/page.tsx
  app/components/AgentStats.tsx
  app/components/Agents.tsx
  app/components/CommentForm.tsx
  app/components/CreateAgentForm.tsx
  app/components/Forums.tsx
  app/components/Header.tsx
  app/components/Hero.tsx
  app/components/SwapCard.tsx
  app/lib/chain-thirdweb.tsx
  app/lib/chain-viem.tsx
Labels: enhancement, !!, mainnet

#127 Fix Market Cap Misalignment in Agent Sorting
  app/components/Agents.tsx
Labels: ui, bug fix, mainnet

#130 Fix navbar not appearing on large screens on load
  app/components/Header.tsx
Labels: enhancement, ui, !!!, mainnet

#129 Create Agent Functionality Card
  app/agent/page.tsx
  app/components/AgentFunctionalityCard.tsx
  app/lib/utils/utils.ts
Labels: enhancement, ui, mainnet

#132 Implement Edit Agent Config
  app/agent/page.tsx
  app/api/agent-data/fetch-agent-data/route.ts
  app/api/agent-data/update-agent-data/route.ts
  app/components/AgentConfiguration.tsx
  app/components/AgentFunctionalityCard.tsx
  app/components/AgentStats.tsx
  app/lib/utils/style/customStyles.ts
Labels: enhancement, ui, !!!, mainnet

#135 Update forum variables
  .gitignore
  app/components/CommentForm.tsx
  app/components/Forums.tsx
Labels: enhancement, backend, !!!
