Repository sparkpointio/sparkagent-launchpad, pull requests merged in 2025-01, with the labels that each got.

#18 Implement Privacy Policy Page
  app/components/Footer.tsx
Labels: documentation, enhancement

#20 Fix Dependency Vulnerabilities Detected by Dependabot
  package-lock.json
  package.json
  yarn.lock
Labels: security

#28 Implement Create Agent Form & Deployment Transactions
  .gitignore
  app/components/CreateAgentForm.tsx
  app/components/Header.tsx
  app/components/Hero.tsx
  app/globals.css
  package-lock.json
  package.json
  yarn.lock
Labels: testnet

#29 Create Agent Page and Fetch/Display Agent Data
  app/agent/page.tsx
  app/api/convert-crypto/route.ts
  app/components/AgentCard.tsx
  app/components/AgentStats.tsx
  app/components/Agents.tsx
  app/components/SparkingProgressCard.tsx
  app/components/SwapCard.tsx
  app/globals.css
  app/lib/assets/index.ts
  app/lib/utils/agents-sample-data.ts
  app/lib/utils/formatting.ts
  app/lib/utils/utils.ts
  package-lock.json
  package.json
  yarn.lock
Labels: ui, testnet

#35 Apply UI Feedback
  app/api/convert-crypto/route.ts
  app/components/AgentFilter.tsx
  app/components/Agents.tsx
  app/components/Header.tsx
  app/components/Hero.tsx
  app/components/SparkAgentLogo.tsx
  app/globals.css
  app/layout.tsx
  app/lib/utils/formatting.ts
Labels: ui, testnet
