Repository sparkpointio/sparkagent-launchpad, pull requests merged in 2025-02, with the labels that each got.

#43 Fix: IPFS Image Upload Using Pinata
  app/components/CreateAgentForm.tsx
Labels: testnet, bug fix

#49 Implement Buying and Selling of Unsparked AI Agent Tokens
  app/components/AgentCard.tsx
  app/components/AgentStats.tsx
  app/components/SwapCard.tsx
  app/components/WalletConfirmationStatus.tsx
  app/lib/assets/index.ts
  app/lib/assets/placeholder-token.png
Labels: enhancement, testnet

#52 47 modify default image of agents using identicon
  app/components/AgentCard.tsx
  app/components/AgentStats.tsx
  app/components/SwapCard.tsx
  app/lib/assets/index.ts
  app/lib/assets/placeholder-token.png
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement, ui, testnet

#53 Improve swap UI and implement 404 on agent page
  .env.example
  app/agent/page.tsx
  app/components/AgentSearchBar.tsx
  app/components/AgentStats.tsx
  app/components/Header.tsx
  app/components/SwapCard.tsx
  app/components/ui/button.tsx
  app/components/ui/not-found.tsx
  app/globals.css
  app/layout.tsx
  bun.lockb
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement, ui, testnet

#54 Add link redirecting to agent page upon agent creation
  app/components/CreateAgentForm.tsx
Labels: enhancement, testnet

#58 Implement Sparking when the target SRK is reached
  app/agent/page.tsx
  app/components/AgentCard.tsx
  app/components/Agents.tsx
  app/components/SparkingProgressCard.tsx
  app/components/SwapCard.tsx
  app/lib/utils/formatting.ts
Labels: enhancement, testnet

#59 UI Improvements
  app/agent/page.tsx
  app/components/AgentCard.tsx
  app/components/AgentStats.tsx
  app/components/CreateAgentForm.tsx
  app/components/WalletConfirmationStatus.tsx
  app/lib/utils/utils.ts
  next.config.ts
Labels: ui, testnet

#69 Fix Dependabot Vulnerability Issues
  package-lock.json
  package.json
  yarn.lock
Labels: security, testnet, !!!, dependencies

#75 Implement Forum Feature and Other changes
  app/agent/page.tsx
  app/api/forums/fetch-forum-messages-count/route.tsx
  app/api/forums/fetch-forum-messages-via-starting-index-number-of-messages-and-direction/route.tsx
  app/components/AgentCard.tsx
  app/components/AgentStats.tsx
  app/components/CommentForm.tsx
  app/components/CreateAgentForm.tsx
  app/components/ForumEntry.tsx
  app/components/Forums.tsx
  app/components/SparkingProgressCard.tsx
  app/components/SwapCard.tsx
  app/lib/utils/formatting.ts
  app/lib/utils/style/customStyles.ts
  app/lib/utils/utils.ts
Labels: enhancement, ui, testnet

#80 Implement fetching of agent tokens from spark agent api
  .env.example
  app/agent/page.tsx
  app/api/tokens/[address]/route.ts
  app/api/tokens/route.ts
  app/components/AgentCard.tsx
  app/components/AgentStats.tsx
  app/components/Agents.tsx
Labels: testnet, !!!

#81 Modify Sell button color to red and Swap button to orange on agents page
  app/components/SwapCard.tsx
  tailwind.config.ts
Labels: ui, testnet

#84 UI Improvements
  app/components/Agents.tsx
  app/components/CommentForm.tsx
  app/components/ForumEntry.tsx
  app/components/Forums.tsx
  package-lock.json
  package.json
  yarn.lock
Labels: ui, testnet, feature-forum

#88 Prepare UI for $SRK airdrop to $OWN and $SFUEL holders
  app/airdrop/page.tsx
  app/components/AgentSearchBar.tsx
  app/components/AgentStats.tsx
  app/components/WalletConfirmationStatus.tsx
  app/lib/assets/index.ts
  app/lib/assets/ownly-logo.png
  app/lib/assets/sfuel-logo.png
Labels: ui, testnet, !

#92 Call Camelot's V2 Router Contract on Buy and Sell when Sparked
  .env.example
  app/components/SwapCard.tsx
  app/components/WalletConfirmationStatus.tsx
Labels: testnet, !!!

#95 Integrate Token Conversion API
  app/api/convert-crypto/fetch-price-conversion/[address]/route.ts
  app/api/convert-crypto/update-price-conversion/route.ts
  app/components/AgentCard.tsx
  app/components/AgentStats.tsx
  app/lib/utils/utils.ts
Labels: testnet, !!!

#96 Fix Camelot DEX label in swap card to display only on sparked tokens
  app/components/SwapCard.tsx
Labels: ui, testnet, !!!

#99 Fix setting of agent token or SRK percentage should be the exact 18 decimal or wei
  app/components/SwapCard.tsx
  app/lib/utils/formatting.ts
Labels: testnet, !!!

#100 Enhance Sorting and Filtering of Agents
  app/components/AgentFilter.tsx
  app/components/AgentSort.tsx
  app/components/AgentStats.tsx
  app/components/Agents.tsx
Labels: enhancement, ui, testnet

#101 Some Improvements to Performance, Accessibility, and UX
  app/components/AgentCard.tsx
  app/components/AgentSearchBar.tsx
  app/components/Agents.tsx
  app/components/Footer.tsx
  app/components/ThirdWebSample.tsx
  app/lib/utils/agents-sample-data.ts
Labels: enhancement, ui, testnet

#102 Update sparking progress computation
  app/agent/page.tsx
  app/components/AgentCard.tsx
  app/components/Agents.tsx
  app/components/WalletConfirmationStatus.tsx
  app/lib/utils/formatting.ts
Labels: testnet, !!!

#103 Further Performance Improvements
  app/components/Agents.tsx
  app/components/Footer.tsx
  app/components/Header.tsx
  app/components/Hero.tsx
  app/components/layout/light-dark-toggle.tsx
Labels: enhancement, testnet, !!

#106 Fix createdAt value in agent stats
  app/agent/page.tsx
  app/components/AgentCard.tsx
  app/components/AgentStats.tsx
  app/components/Agents.tsx
  app/lib/utils/formatting.ts
Labels: enhancement, ui, testnet, !!!

#107 Improve placeholders and add more context on the purchase amount
  app/components/CreateAgentForm.tsx
Labels: enhancement, ui, testnet, !!!

#108 Update NEXT_PUBLIC_FPAIR to NEXT_PUBLIC_FROUTER in env
  .env.example
  app/components/SwapCard.tsx
  app/components/WalletConfirmationStatus.tsx
Labels: testnet, !!!

#112 Fix SRK balance formatting
  app/components/CreateAgentForm.tsx
Labels: ui, testnet, bug fix

#113 Fix agent form and forum fee issues
  app/components/CommentForm.tsx
  app/components/CreateAgentForm.tsx
Labels: testnet, bug fix

#114 Modify arbitrumsepolia calls to arbitrum
  app/agent/page.tsx
  app/components/AgentStats.tsx
  app/components/Agents.tsx
  app/components/CommentForm.tsx
  app/components/CreateAgentForm.tsx
  app/components/Forums.tsx
  app/components/Header.tsx
  app/components/Hero.tsx
  app/components/SwapCard.tsx
Labels: !!!, mainnet
